name: documentation

on:
  push:
      branches: [ "newVersion" ]
  pull_request:
      types: [opened, ready_for_review, closed]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Set up MATLAB
        uses: matlab-actions/setup-matlab@v2
        with:
          release: R2023a
      - name: Install MATLAB Engine
        run: |
          MATLAB_ROOT=$(matlab -nojvm -r "disp(matlabroot); exit" | tail -n 1)
          echo "MATLAB root directory: $MATLAB_ROOT"
          cd "$MATLAB_ROOT/extern/engines/python"
          python setup.py install
      - name: Install dependencies
        run: |
          pip install -r docs/requirements.txt
      - name: Sphinx build
        run: |
          sphinx-build docs/ docs/_build/
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/newVersion' }}
        with:
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/_build/
          force_orphan: true
